# Server
server:
  port: 8080

# Eureka Discovery Client Consumer
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-service.prod/eureka

#redis
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: redis-server.prod
    port: 6379